# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.find_partner_invoice_items200_response import FindPartnerInvoiceItems200Response

class TestFindPartnerInvoiceItems200Response(unittest.TestCase):
    """FindPartnerInvoiceItems200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindPartnerInvoiceItems200Response:
        """Test FindPartnerInvoiceItems200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindPartnerInvoiceItems200Response`
        """
        model = FindPartnerInvoiceItems200Response()
        if include_optional:
            return FindPartnerInvoiceItems200Response(
                content = [
                    tl_pax8.models.invoice_item.InvoiceItem(
                        id = '', 
                        purchase_order_number = '', 
                        type = 'rebate', 
                        company_id = '', 
                        external_id = '', 
                        company_name = '', 
                        start_period = '', 
                        end_period = '', 
                        quantity = 1.337, 
                        unit_of_measure = '', 
                        term = '3 Year', 
                        sku = '', 
                        description = '', 
                        details = '', 
                        rate_type = 'markup (Percentage based markup over to be determined base cost)', 
                        charge_type = 'flat', 
                        price = 1.337, 
                        sub_total = 1.337, 
                        cost = 1.337, 
                        cost_total = 1.337, 
                        offered_by = '', 
                        billed_by_pax8 = True, 
                        total = 1.337, 
                        product_id = '', 
                        product_name = '', 
                        billing_fee = 1.337, 
                        billing_fee_rate = 1.337, 
                        amount_due = 1.337, 
                        currency_code = '', 
                        subscription_id = '', )
                    ],
                page = tl_pax8.models.page.Page(
                    size = 50, 
                    total_elements = 237, 
                    total_pages = 5, 
                    number = 1, )
            )
        else:
            return FindPartnerInvoiceItems200Response(
        )
        """

    def testFindPartnerInvoiceItems200Response(self):
        """Test FindPartnerInvoiceItems200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
