# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.contact import Contact

class TestContact(unittest.TestCase):
    """Contact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Contact:
        """Test Contact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Contact`
        """
        model = Contact()
        if include_optional:
            return Contact(
                id = '18d6329e-93f9-46a5-9df7-37e4c29d2840',
                first_name = 'John',
                last_name = 'Doe',
                email = 'john@doe.com',
                phone = '555-555-5555',
                created_date = '2020-05-12',
                types = [
                    tl_pax8.models.contact_type.ContactType(
                        type = 'Admin', 
                        primary = True, )
                    ]
            )
        else:
            return Contact(
                first_name = 'John',
                last_name = 'Doe',
                email = 'john@doe.com',
                phone = '555-555-5555',
        )
        """

    def testContact(self):
        """Test Contact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
