# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.find_partner_invoices200_response import FindPartnerInvoices200Response

class TestFindPartnerInvoices200Response(unittest.TestCase):
    """FindPartnerInvoices200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindPartnerInvoices200Response:
        """Test FindPartnerInvoices200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindPartnerInvoices200Response`
        """
        model = FindPartnerInvoices200Response()
        if include_optional:
            return FindPartnerInvoices200Response(
                content = [
                    tl_pax8.models.invoice.Invoice(
                        id = '', 
                        invoice_date = '', 
                        due_date = '', 
                        balance = 1.337, 
                        carried_balance = 1.337, 
                        total = 1.337, 
                        currency_code = '', 
                        partner_name = '', 
                        company_id = '', 
                        external_id = '', )
                    ],
                page = tl_pax8.models.page.Page(
                    size = 50, 
                    total_elements = 237, 
                    total_pages = 5, 
                    number = 1, )
            )
        else:
            return FindPartnerInvoices200Response(
        )
        """

    def testFindPartnerInvoices200Response(self):
        """Test FindPartnerInvoices200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
