# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.provisioning_detail import ProvisioningDetail

class TestProvisioningDetail(unittest.TestCase):
    """ProvisioningDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProvisioningDetail:
        """Test ProvisioningDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProvisioningDetail`
        """
        model = ProvisioningDetail()
        if include_optional:
            return ProvisioningDetail(
                label = '',
                key = 'userEmailAddress',
                values = [
                    ''
                    ],
                description = 'Provide the user's email address',
                value_type = 'Input',
                possible_values = [
                    ''
                    ]
            )
        else:
            return ProvisioningDetail(
        )
        """

    def testProvisioningDetail(self):
        """Test ProvisioningDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
