# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.commitment import Commitment

class TestCommitment(unittest.TestCase):
    """Commitment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Commitment:
        """Test Commitment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Commitment`
        """
        model = Commitment()
        if include_optional:
            return Commitment(
                id = '',
                term = '3-Year',
                auto_renew = True,
                renewal_window_days_before_term_end = 1.337,
                renewal_window_days_after_term_end = 1.337,
                allow_for_quantity_increase = True,
                allow_for_quantity_decrease = True,
                allow_for_early_cancellation = True,
                cancellation_fee_applied = True,
                is_transferable = True
            )
        else:
            return Commitment(
        )
        """

    def testCommitment(self):
        """Test Commitment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
