# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.usage_line import UsageLine

class TestUsageLine(unittest.TestCase):
    """UsageLine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageLine:
        """Test UsageLine
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageLine`
        """
        model = UsageLine()
        if include_optional:
            return UsageLine(
                usage_summary_id = '',
                usage_date = '',
                product_name = '',
                product_id = '',
                unit_of_measure = '',
                quantity = 1.337,
                current_charges = 1.337,
                current_profit = 1.337,
                partner_total = 1.337,
                unit_price = 1.337,
                currency_code = '',
                is_trial = True
            )
        else:
            return UsageLine(
        )
        """

    def testUsageLine(self):
        """Test UsageLine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
