# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.find_all_products200_response import FindAllProducts200Response

class TestFindAllProducts200Response(unittest.TestCase):
    """FindAllProducts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindAllProducts200Response:
        """Test FindAllProducts200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindAllProducts200Response`
        """
        model = FindAllProducts200Response()
        if include_optional:
            return FindAllProducts200Response(
                content = [
                    tl_pax8.models.product.Product(
                        id = '', 
                        name = 'Acme Corps Productivity Suite', 
                        vendor_name = 'Acme Corps', 
                        short_description = 'Short description about the product to sell', 
                        sku = '4225-776-3234', 
                        vendor_sku = '12345-AA-XYZ', 
                        alt_vendor_sku = '', 
                        requires_commitment = False, )
                    ],
                page = tl_pax8.models.page.Page(
                    size = 50, 
                    total_elements = 237, 
                    total_pages = 5, 
                    number = 1, )
            )
        else:
            return FindAllProducts200Response(
        )
        """

    def testFindAllProducts200Response(self):
        """Test FindAllProducts200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
