# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.api.companies_api import CompaniesApi


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompaniesApi()

    def tearDown(self) -> None:
        pass

    def test_companies_company_id_get(self) -> None:
        """Test case for companies_company_id_get

        Fetch a single company record by companyId
        """
        pass

    def test_create_company(self) -> None:
        """Test case for create_company

        Create a new Company
        """
        pass

    def test_find_companies(self) -> None:
        """Test case for find_companies

        Fetch a paginated list of your companies
        """
        pass

    def test_update_company(self) -> None:
        """Test case for update_company

        Update an existing Company
        """
        pass


if __name__ == '__main__':
    unittest.main()
