# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.pricing import Pricing

class TestPricing(unittest.TestCase):
    """Pricing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Pricing:
        """Test Pricing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Pricing`
        """
        model = Pricing()
        if include_optional:
            return Pricing(
                billing_term = 'Monthly',
                commitment_term = '3-Year',
                commitment_term_in_months = 36,
                type = 'Flat',
                unit_of_measurement = 'Each',
                rates = [
                    tl_pax8.models.rate.Rate(
                        partner_buy_rate = 145.8, 
                        suggested_retail_price = 151.8, 
                        start_quantity_range = 5, 
                        end_quantity_range = 200, 
                        charge_type = 'Per Unit', )
                    ]
            )
        else:
            return Pricing(
        )
        """

    def testPricing(self):
        """Test Pricing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
