# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.product_dependency import ProductDependency

class TestProductDependency(unittest.TestCase):
    """ProductDependency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductDependency:
        """Test ProductDependency
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductDependency`
        """
        model = ProductDependency()
        if include_optional:
            return ProductDependency(
                name = '',
                products = [
                    tl_pax8.models.product.Product(
                        id = '', 
                        name = 'Acme Corps Productivity Suite', 
                        vendor_name = 'Acme Corps', 
                        short_description = 'Short description about the product to sell', 
                        sku = '4225-776-3234', 
                        vendor_sku = '12345-AA-XYZ', 
                        alt_vendor_sku = '', 
                        requires_commitment = False, )
                    ]
            )
        else:
            return ProductDependency(
        )
        """

    def testProductDependency(self):
        """Test ProductDependency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
