# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.find_provision_details_by_product_id200_response import FindProvisionDetailsByProductId200Response

class TestFindProvisionDetailsByProductId200Response(unittest.TestCase):
    """FindProvisionDetailsByProductId200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindProvisionDetailsByProductId200Response:
        """Test FindProvisionDetailsByProductId200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindProvisionDetailsByProductId200Response`
        """
        model = FindProvisionDetailsByProductId200Response()
        if include_optional:
            return FindProvisionDetailsByProductId200Response(
                content = [
                    tl_pax8.models.provisioning_detail.ProvisioningDetail(
                        label = '', 
                        key = 'userEmailAddress', 
                        values = [
                            ''
                            ], 
                        description = 'Provide the user's email address', 
                        value_type = 'Input', 
                        possible_values = [
                            ''
                            ], )
                    ]
            )
        else:
            return FindProvisionDetailsByProductId200Response(
        )
        """

    def testFindProvisionDetailsByProductId200Response(self):
        """Test FindProvisionDetailsByProductId200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
