# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.api.invoices_api import InvoicesApi


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoicesApi()

    def tearDown(self) -> None:
        pass

    def test_find_partner_invoice_items(self) -> None:
        """Test case for find_partner_invoice_items

        Fetch a paginated list of items for an invoice
        """
        pass

    def test_find_partner_invoices(self) -> None:
        """Test case for find_partner_invoices

        Fetch a paginated list of invoices
        """
        pass

    def test_get_partner_invoice(self) -> None:
        """Test case for get_partner_invoice

        Fetch an invoice by invoiceId
        """
        pass


if __name__ == '__main__':
    unittest.main()
