# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.find_subscription_usage_summaries200_response import FindSubscriptionUsageSummaries200Response

class TestFindSubscriptionUsageSummaries200Response(unittest.TestCase):
    """FindSubscriptionUsageSummaries200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindSubscriptionUsageSummaries200Response:
        """Test FindSubscriptionUsageSummaries200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindSubscriptionUsageSummaries200Response`
        """
        model = FindSubscriptionUsageSummaries200Response()
        if include_optional:
            return FindSubscriptionUsageSummaries200Response(
                content = [
                    tl_pax8.models.usage_summary.UsageSummary(
                        id = '', 
                        company_id = '', 
                        product_id = '', 
                        resource_group = '', 
                        vendor_name = '', 
                        current_charges = 1.337, 
                        currency_code = '', 
                        partner_total = 1.337, 
                        is_trial = True, )
                    ],
                page = tl_pax8.models.page.Page(
                    size = 50, 
                    total_elements = 237, 
                    total_pages = 5, 
                    number = 1, )
            )
        else:
            return FindSubscriptionUsageSummaries200Response(
        )
        """

    def testFindSubscriptionUsageSummaries200Response(self):
        """Test FindSubscriptionUsageSummaries200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
