# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.api.contacts_api import ContactsApi


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactsApi()

    def tearDown(self) -> None:
        pass

    def test_companies_company_id_contacts_contact_id_delete(self) -> None:
        """Test case for companies_company_id_contacts_contact_id_delete

        Delete a contact
        """
        pass

    def test_companies_company_id_contacts_contact_id_get(self) -> None:
        """Test case for companies_company_id_contacts_contact_id_get

        Fetch a contact
        """
        pass

    def test_companies_company_id_contacts_contact_id_put(self) -> None:
        """Test case for companies_company_id_contacts_contact_id_put

        Update a contact
        """
        pass

    def test_companies_company_id_contacts_get(self) -> None:
        """Test case for companies_company_id_contacts_get

        Fetch a paginated list of contacts
        """
        pass

    def test_companies_company_id_contacts_post(self) -> None:
        """Test case for companies_company_id_contacts_post

        Create a new Contact
        """
        pass


if __name__ == '__main__':
    unittest.main()
