# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_find_subscription_by_subscription_id(self) -> None:
        """Test case for find_subscription_by_subscription_id

        Fetch a subscription by subscriptionId
        """
        pass

    def test_find_subscription_history_by_subscription_id(self) -> None:
        """Test case for find_subscription_history_by_subscription_id

        Fetch the history of a subscription
        """
        pass

    def test_find_subscriptions(self) -> None:
        """Test case for find_subscriptions

        Fetch a paginated list of subscriptions
        """
        pass

    def test_subscriptions_subscription_id_delete(self) -> None:
        """Test case for subscriptions_subscription_id_delete

        Cancel a subscription
        """
        pass

    def test_update_subscription(self) -> None:
        """Test case for update_subscription

        Update a specified subscription
        """
        pass


if __name__ == '__main__':
    unittest.main()
