# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.token_request import TokenRequest

class TestTokenRequest(unittest.TestCase):
    """TokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenRequest:
        """Test TokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenRequest`
        """
        model = TokenRequest()
        if include_optional:
            return TokenRequest(
                client_id = '',
                client_secret = '',
                audience = 'https://api.pax8.com',
                grant_type = 'client_credentials'
            )
        else:
            return TokenRequest(
                client_id = '',
                client_secret = '',
                audience = 'https://api.pax8.com',
                grant_type = 'client_credentials',
        )
        """

    def testTokenRequest(self):
        """Test TokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
