# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.find_companies200_response import FindCompanies200Response

class TestFindCompanies200Response(unittest.TestCase):
    """FindCompanies200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindCompanies200Response:
        """Test FindCompanies200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindCompanies200Response`
        """
        model = FindCompanies200Response()
        if include_optional:
            return FindCompanies200Response(
                content = [
                    tl_pax8.models.company.Company(
                        id = '', 
                        name = 'Pax8', 
                        address = tl_pax8.models.address.Address(
                            street = '5500 S Quebec St', 
                            street2 = 'Ste. 350', 
                            city = 'Greenwood Village', 
                            state_or_province = 'CO', 
                            postal_code = '80111', 
                            country = 'US', ), 
                        phone = '555-555-5555', 
                        website = 'https://www.pax8.com/', 
                        external_id = '', 
                        bill_on_behalf_of_enabled = True, 
                        self_service_allowed = True, 
                        order_approval_required = True, 
                        status = 'Active', 
                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                page = tl_pax8.models.page.Page(
                    size = 50, 
                    total_elements = 237, 
                    total_pages = 5, 
                    number = 1, )
            )
        else:
            return FindCompanies200Response(
        )
        """

    def testFindCompanies200Response(self):
        """Test FindCompanies200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
