# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.find_usage_lines200_response import FindUsageLines200Response

class TestFindUsageLines200Response(unittest.TestCase):
    """FindUsageLines200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindUsageLines200Response:
        """Test FindUsageLines200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindUsageLines200Response`
        """
        model = FindUsageLines200Response()
        if include_optional:
            return FindUsageLines200Response(
                content = [
                    tl_pax8.models.usage_line.UsageLine(
                        usage_summary_id = '', 
                        usage_date = '', 
                        product_name = '', 
                        product_id = '', 
                        unit_of_measure = '', 
                        quantity = 1.337, 
                        current_charges = 1.337, 
                        current_profit = 1.337, 
                        partner_total = 1.337, 
                        unit_price = 1.337, 
                        currency_code = '', 
                        is_trial = True, )
                    ],
                page = tl_pax8.models.page.Page(
                    size = 50, 
                    total_elements = 237, 
                    total_pages = 5, 
                    number = 1, )
            )
        else:
            return FindUsageLines200Response(
        )
        """

    def testFindUsageLines200Response(self):
        """Test FindUsageLines200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
