# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.models.usage_summary import UsageSummary

class TestUsageSummary(unittest.TestCase):
    """UsageSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageSummary:
        """Test UsageSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageSummary`
        """
        model = UsageSummary()
        if include_optional:
            return UsageSummary(
                id = '',
                company_id = '',
                product_id = '',
                resource_group = '',
                vendor_name = '',
                current_charges = 1.337,
                currency_code = '',
                partner_total = 1.337,
                is_trial = True
            )
        else:
            return UsageSummary(
        )
        """

    def testUsageSummary(self):
        """Test UsageSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
