# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tl_pax8.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_create_order(self) -> None:
        """Test case for create_order

        Create a new order for a specified company
        """
        pass

    def test_find_orders(self) -> None:
        """Test case for find_orders

        Fetch a paginated list of orders associated with your partner
        """
        pass

    def test_find_orders_by_order_id(self) -> None:
        """Test case for find_orders_by_order_id

        Fetch order details by orderId
        """
        pass


if __name__ == '__main__':
    unittest.main()
