# coding: utf-8

"""
    Authentication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProvisioningDetail(BaseModel):
    """
    ProvisioningDetail
    """ # noqa: E501
    label: Optional[StrictStr] = Field(default=None, description="The label to display")
    key: Optional[StrictStr] = Field(default=None, description="The key")
    values: Optional[List[StrictStr]] = Field(default=None, description="A list of values based on the ```valuetype``` and ```possibleValues```")
    description: Optional[StrictStr] = Field(default=None, description="Instructions and context to help enter the required provisioning information")
    value_type: Optional[StrictStr] = Field(default=None, description="Provisioning Detail Value Type:  * `Input` - A value that is supplied by a user  * `Single-Value` - A single value that is picked from the `possibleValues` list  * `Multi-Value` - One or multiple values that are picked from the `possibleValues` list ", alias="valueType")
    possible_values: Optional[List[StrictStr]] = Field(default=None, description="A list of possible values. `possibleValues` will be null when `valueType` is `Input`", alias="possibleValues")
    __properties: ClassVar[List[str]] = ["label", "key", "values", "description", "valueType", "possibleValues"]

    @field_validator('value_type')
    def value_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Input', 'Single-Value', 'Multi-Value']):
            raise ValueError("must be one of enum values ('Input', 'Single-Value', 'Multi-Value')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProvisioningDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "label",
            "description",
            "value_type",
            "possible_values",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProvisioningDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "label": obj.get("label"),
            "key": obj.get("key"),
            "values": obj.get("values"),
            "description": obj.get("description"),
            "valueType": obj.get("valueType"),
            "possibleValues": obj.get("possibleValues")
        })
        return _obj


